=== carlosc20/DWeb2019/common/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (metadata,workteam,abstract,deliverables?)>

<!ELEMENT metadata (keyname,title,subtitle?,supervisor,bdate,edate) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT bdate (#PCDATA) >
<!ELEMENT edate (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
            homepage CDATA #IMPLIED >

<!ELEMENT workteam (worker+) >
<!ELEMENT worker (identifier,name,email,git?) >
<!ELEMENT identifier (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT git (#PCDATA) >

<!ELEMENT abstract (p+) >
<!ELEMENT p (#PCDATA|b|i|u|xref)* >
<!ELEMENT b (#PCDATA|i|u|xref)* >
<!ELEMENT i (#PCDATA|b|u|xref)* >
<!ELEMENT u (#PCDATA|b|i|xref)* >
<!ELEMENT xref (#PCDATA) >
<!ATTLIST xref
            url CDATA #REQUIRED >
            
<!ELEMENT deliverables (deliverable+) >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable
            path CDATA #REQUIRED >

=== carlosc20/DWeb2019/TP8/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../common/PR.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>TPC8</title>
        <supervisor homepage="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
        <bdate>5/11/2019</bdate>
        <edate>12/11/2019</edate>
    </metadata>
    <workteam>
        <worker>
            <identifier>A81946</identifier>
            <name>Carlos Peixoto Antunes de Castro</name>
            <email>a81946@alunos.uminho.pt</email>
            <git>https://github.com/carlosc20</git>
        </worker>
    </workteam>
    <abstract>
        <p>Criação de um servidor em node.js usando express e mongoose para responder a pedidos GET de uma base de dados de Prémios Nobel.</p>
        <p>Foram criadas duas APIs, uma que responde em / e fornece a interface, e outra que responde em /api que fornece dados em json (Exercício 1 <xref url="http://www4.di.uminho.pt/~jcr/AULAS/didac/RepFichas/site/fichas/dweb2019-e2.html">dweb2019-e2</xref>) à primeira.</p>
    </abstract>
    <deliverables>
        <deliverable path="nobel">Diretoria do projeto</deliverable>
    </deliverables>
</pr>

=== carlosc20/DWeb2019/TP7/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../common/PR.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>TPC7</title>
        <supervisor homepage="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
        <bdate>29/10/2019</bdate>
        <edate>5/11/2019</edate>
    </metadata>
    <workteam>
        <worker>
            <identifier>A81946</identifier>
            <name>Carlos Peixoto Antunes de Castro</name>
            <email>a81946@alunos.uminho.pt</email>
            <git>https://github.com/carlosc20</git>
        </worker>
    </workteam>
    <abstract>
        <p>Criação de 3 queries de mongoDB.</p>
        <p>Criação de um servidor em node.js usando express e mongoose para responder a operações CRUD sobre uma bases de dados de filmes americanos.</p>
    </abstract>
    <deliverables>
        <deliverable path="filmes">Servidor node.js</deliverable>
        <deliverable path="queries.txt">Queries de mongodb</deliverable>
    </deliverables>
</pr>

=== carlosc20/DWeb2019/TP5/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../common/PR.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>TPC5</title>
        <supervisor homepage="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
        <bdate>15/10/2019</bdate>
        <edate>21/10/2019</edate>
    </metadata>
    <workteam>
        <worker>
            <identifier>A81946</identifier>
            <name>Carlos Peixoto Antunes de Castro</name>
            <email>a81946@alunos.uminho.pt</email>
            <git>https://github.com/carlosc20</git>
        </worker>
    </workteam>
    <abstract>
        <p>Este projeto consiste num servidor node.js que fornece uma página html com uma lista de tarefas, com a opção de adicionar novas tarefas.</p>
        <p>A página html é gerada a partir da ferramenta de template pug.</p>
    </abstract>
    <deliverables>
        <deliverable path="todolist.js">Servidor node.js (JS)</deliverable>
        <deliverable path="layout.pug">Template do html do layout (PUG)</deliverable>
        <deliverable path="index.pug">Template do html da página principal (PUG)</deliverable>
        <deliverable path="erro.pug">Template do html da página de erro (PUG)</deliverable>
        <deliverable path="stylesheets/w3.css">CSS usado (CSS)</deliverable>
    </deliverables>
</pr>

=== carlosc20/DWeb2019/TP4/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../common/PR.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>TPC4</title>
        <supervisor homepage="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
        <bdate>8/10/2019</bdate>
        <edate>14/10/2019</edate>
    </metadata>
    <workteam>
        <worker>
            <identifier>A81946</identifier>
            <name>Carlos Peixoto Antunes de Castro</name>
            <email>a81946@alunos.uminho.pt</email>
            <git>https://github.com/carlosc20</git>
        </worker>
    </workteam>
    <abstract>
        <p>Este projeto consiste em várias partes, usando o <xref url=" http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/arq.xml">dataset dos arqueossítios em XML</xref>:</p>
        <p>Uma stylesheet XSLT que processe este ficheiro e gere um ficheiro por cada arqueossítio e os coloque numa pasta: arq1.xsml, arq2.xml...</p>
        <p>Uma stylesheet que esteja associada aos ficheiros XML gerados e os transforme em HTML.</p>
        <p>Um servidor em nodejs que serva os ficheiros, ou seja, responde aos pedidos: localhost:7777/3  --> Coloca no browser o conteúdo do arq3.xml em formato HTML.</p>
    </abstract>
    <deliverables>
        <deliverable path="arq-split.xsl">XSL usado para garar o XML dos arqueossítios individuais (XSL)</deliverable>
        <deliverable path="arq2html.xsl">XSL usado para gerar HTML dos arqueossítios (XSL)</deliverable>
        <deliverable path="server.js">Servidor node.js (JS)</deliverable>
    </deliverables>
</pr>

=== carlosc20/DWeb2019/TP9/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../common/PR.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>TPC9</title>
        <supervisor homepage="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
        <bdate>12/11/2019</bdate>
        <edate>18/11/2019</edate>
    </metadata>
    <workteam>
        <worker>
            <identifier>A81946</identifier>
            <name>Carlos Peixoto Antunes de Castro</name>
            <email>a81946@alunos.uminho.pt</email>
            <git>https://github.com/carlosc20</git>
        </worker>
    </workteam>
    <abstract>
        <p>Aplicação em node.js que permite criar uma collection em mongodb a partir de um ficheiro json.</p>
    </abstract>
    <deliverables>
        <deliverable path="mongoimport.js">Aplicação mongoimport</deliverable>
        <deliverable path="exemplo.txt">Exemplo de como executar.</deliverable>
    </deliverables>
</pr>

=== carlosc20/DWeb2019/TESTE/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../common/PR.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>TESTE</title>
        <supervisor homepage="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
        <bdate>16/1/2020</bdate>
        <edate>16/1/2020</edate>
    </metadata>
    <workteam>
        <worker>
            <identifier>A81946</identifier>
            <name>Carlos Peixoto Antunes de Castro</name>
            <email>a81946@alunos.uminho.pt</email>
            <git>https://github.com/carlosc20</git>
        </worker>
    </workteam>
    <abstract>
        <p>Resolução de um teste (http://www4.di.uminho.pt/~jcr/AULAS/didac/RepFichas/site/fichas/daw2020-e1.html) que consiste em dois exercícios de desenvolvimento de aplicações web utilizando Node e Express.</p>
        <p>No exercício 1, o dataset fornecido foi convertido para json utilizando um conversor online (https://www.freeformatter.com/xml-to-json-converter.html).
        A persistência foi feita usando MongoDB, e o dataset em json foi importado com o comando "mongoimport -d obras -c obras --jsonArray arquivo.json".
        Para além de ter o MongoDB (na porta padrão 27017) não é necessário qualquer requisito adicional.</p>
        <p>O exercíco 2 para além do pedido disponibiliza também uma página de acesso ás tipologias, semelhante á da entidade.</p>
        <p>Ambos os servidores correm na porta 3000 por definição.</p>
    </abstract>
    <deliverables>
        <deliverable path="arquivo">Exercício Nº 1: Arquivo de Música Digital</deliverable>
        <deliverable path="arquivo/arquivo.json">Exercício Nº 1, dataset transformado</deliverable>
        <deliverable path="clav">Exercício Nº 2: CLAV: Classificação e Avaliação da Informação Pública</deliverable>
        <deliverable path="clav/api.txt">Exercício Nº 2, "aquecimento"</deliverable>
    </deliverables>
</pr>

=== carlosc20/DWeb2019/TP3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>TP3</title>
        <supervisor homepage="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
        <bdate>1/10/2019</bdate>
        <edate>8/10/2019</edate>
    </metadata>
    <workteam>
        <worker>
            <identifier>A81946</identifier>
            <name>Carlos Peixoto Antunes de Castro</name>
            <email>a81946@alunos.uminho.pt</email>
            <git>https://github.com/carlosc20</git>
        </worker>
    </workteam>
    <abstract>
        <p>Criação de um XSL para transformar o pr.xml em uma página html.</p>
        <p>Criação de um XSL para transformar o xml dos arqueosítios em várias páginas hmtl, nomeadamente um índice e uma página por arqueosítio.</p>
    </abstract>
    <deliverables>
        <deliverable path="pr.hmtl">(HTML)</deliverable>
        <deliverable path="pr.xsl">(XSL)</deliverable>
        <deliverable path="arq.xsl"></deliverable>
        <deliverable path="arq/index.html"></deliverable>
    </deliverables>
</pr>

=== carlosc20/DWeb2019/TP6/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../common/PR.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>TPC6</title>
        <supervisor homepage="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
        <bdate>22/10/2019</bdate>
        <edate>28/10/2019</edate>
    </metadata>
    <workteam>
        <worker>
            <identifier>A81946</identifier>
            <name>Carlos Peixoto Antunes de Castro</name>
            <email>a81946@alunos.uminho.pt</email>
            <git>https://github.com/carlosc20</git>
        </worker>
    </workteam>
    <abstract>
        <p>Servidor em node.js usando a framework express que permite realizar operações CRUD sobre um ficheiro JSON que contém o Arquivo Sonoro de Ernesto Veiga de Oliveira.</p>
    </abstract>
    <deliverables>
        <deliverable path="tp6">Diretoria do servidor node.js</deliverable>
    </deliverables>
</pr>
